const dog1Array = [  /// -2 off line number
    "Akita",
    "American Eskimo Dog",
    "Australian Cattle Dog",          
    "Australian Shepherd", 
    "Basset Hound",            
    "Beagle", 
    "Bernese Mountain Dog",                        
    "Bichon Frise",                   
    "Border Collie",                  
    "Boston Terrier",
    "Boxer",
    "Bulldog",
    "Cavalier King Charles Spaniel",   
    "Chihuahua",                      
    "Cocker Spaniel",   
    "Corgi",              
    "Dachshund",
    "Dalmation",
    "German Shepherd",                     
    "Golden Retriever",           
    "Husky",
    "Jack Russell",                   
    "Labrador", 
    "Malamute",                      
    "Maltese",                        
    "Papillon",                      
    "Pekingese",
    "Pomeranian",                      
    "Poodle",                         
    "Pug", 
    "Rottweiler",                           
    "Schnauzer",                      
    "Shar-Pei", 
    "Shetland Sheepdog",     
    "Shih-Tzu",
    "Springer Spaniel",                                         
    "Yorkie"                         
];

let crossbeeds = {
    Alaskan_Shepherd: ["German Shepherd", "Malamute"],
    Augie: ["Australian Shepherd", "Corgi"],
    Ausky: ["Australian Cattle Dog", "Husky"],
    Aussiedoodle: ["Australian Shepherd", "Poodle"],
    Bagle: ["Basset Hound", "Beagle"],
    Baskimo: ["American Eskimo Dog", "Basset Hound"],
    Bassador: ["Basset Hound", "Labrador"],
    Baussie: ["Australian Shepherd", "Boston Terrier"],
    Beabull: ["Beagle", "Bulldog"],
    Beagi: ["Beagle", "Corgi"],
    Beaglier: ["Beagle", "Cavalier King Charles Spaniel"],
    Bichpoo: ["Bichon Frise", "Poodle"],
    Bo_Chi: ["Boston Terrier", "Chihuahua"],
    Boglen_Terrier: ["Beagle", "Boston Terrier"],
    Borador: ["Border Collie", "Labrador"],
    Border_Aussie: ["Australian Shepherd", "Border Collie"],
    Border_Heeler: ["Australian Cattle Dog", "Border Collie"],
    Border_Jack: ["Border Collie", "Jack Russell"],
    Bordernese: ["Bernese Mountain Dog", "Border Collie"],
    Borgi: ["Border Collie", "Corgi"],
    BoShih: ["Boston Terrier", "Shih-Tzu"],
    Boxador: ["Boxer", "Labrador"],
    Boxksy: ["Boxer", "Husky"],
    Boxpei: ["Boxer", "Shar-Pei"],
    Boxweiler: ["Boxer", "Rottweiler"],
    Bugg: ["Boston Terrier", "Pug"],
    Bullmatian: ["Bulldog", "Dalmation"],
    Bullpei: ["Bulldog", "Shar-Pei"],
    Cattlegi: ["Australian Cattle Dog", "Corgi"],
    Cavachon: ["Bichon Frise", "Cavalier King Charles Spaniel"],
    Cavapoo: ["Cavalier King Charles Spaniel", "Poodle"],
    Cheeks: ["Chihuahua", "Pekingese"],
    Chigi: ["Chihuahua", "Corgi"],
    Chion: ["Chihuahua", "Papillon"],
    Chiweenie: ["Chihuahua", "Dachshund"],
    Chorkie: ["Chihuahua", "Yorkie"],
    Chug: ["Chihuahua", "Pug"],
    Cockalier: ["Cavalier King Charles Spaniel", "Cocker Spaniel"],
    Cockapoo: ["Cocker Spaniel", "Poodle"],
    Cocker_Corgi: ["Cocker Spaniel", "Corgi"],
    Cojack: ["Corgi", "Jack Russell"],
    Corger: ["Boxer", "Corgi"],
    Corgi_Basset: ["Basset Hound", "Corgi"],
    Corgidor: ["Corgi", "Labrador"],
    Corgipom: ["Corgi", "Pomeranian"],
    Corgipoo: ["Corgi", "Poodle"],
    Corgitian: ["Corgi", "Dalmation"],
    Corgoyed: ["Corgi", "Samoyed"],
    Corillon: ["Corgi", "Papillon"],
    Corkie: ["Cocker Spaniel", "Yorkie"],
    Corman_Shepherd: ["Corgi", "German Shepherd"],
    Dalmador: ["Dalmation", "Labrador"],
    Daug: ["Dachshund", "Pug"],
    Docker: ["Cocker Spaniel", "Dachshund"],
    Dorkie: ["Dachshund", "Yorkie"],
    Doxiepoo: ["Dachshund", "Poodle"],
    Doxle: ["Beagle", "Dachshund"],
    Eskijack: ["American Eskimo Dog", "Jack Russell"],
    Eskland: ["American Eskimo Dog", "Shetland Sheepdog"],
    Gerberian_Shepsky: ["German Shepherd", "Husky"],
    Goldador: ["Golden Retriever", "Labrador"],
    Corgiever: ["Corgi", "Golden Retriever"],
    Golden_Dox: ["Dachshund", "Golden Retriever"],
    Goldendoodle: ["Golden Retriever", "Poodle"],
    Gollie: ["Border Collie", "Golden Retriever"],
    Horgi: ["Corgi", "Husky"],
    Huskamute: ["Husky", "Malamute"],
    Jackabee: ["Beagle", "Jack Russell"],
    Jackapoo: ["Jack Russell", "Poodle"],
    Jug: ["Jack Russell", "Pug"],
    Labbe: ["Beagle", "Labrador"],
    Labpei: ["Labrador", "Shar-Pei"],
    Labradoodle: ["Labrador", "Poodle"],
    Labrashepherd: ["German Shepherd", "Labrador"],
    Mal_Shi: ["Maltese", "Shih-Tzu"],
    Mini_Hippo: ["Cocker Spaniel", "Shar-Pei"],
    Miniature_Boxer: ["Boston Terrier", "Boxer"],
    Miniature_Bulldog: ["Bulldog", "Pug"],
    Maltichon: ["Bichon Frise", "Maltese"],
    Maltipoo: ["Maltese", "Poodle"],
    Morkie: ["Maltese", "Yorkie"],
    Ori_Pei: ["Pug", "Shar-Pei"],
    Papastzu: ["Papillon", "Shih-Tzu"],
    Papipoo: ["Papillon", "Poodle"],
    Pekeapoo: ["Pekingese", "Poodle"],
    Pembroke_Sheltie: ["Corgi", "Shetland Sheepdog"],
    Pomapoo: ["Pomeranian", "Poodle"],
    Pomchi: ["Chihuahua", "Pomeranian"],
    Porgi: ["Corgi", "Pug"],
    Pug_Zu: ["Pug", "Shih-Tzu"],
    Pugalier: ["Cavalier King Charles Spaniel", "Pug"],
    Puggle: ["Beagle", "Pug"],
    Puginese: ["Pekingese", "Pug"],
    Rottgi: ["Corgi", "Rottweiler"],
    Schnoodle: ["Poodle", "Schnauzer"],
    Schnorgi: ["Corgi", "Schnauzer"],
    Schnug: ["Pug", "Schnauzer"],
    Sharberian_Husky: ["Husky", "Shar-Pei"],
    Sheepgi: ["Corgi", "Sheepdog"],
    Sheltie_Heeler: ["Australian Cattle Dog", "Shetland Sheepdog"],
    Sheltie_Shepherd: ["German Shepherd", "Shetland Sheepdog"],
    Sheltiedoodle: ["Poodle", "Shetland Sheepdog"],
    Shepkita: ["Akita", "German Shepherd"],
    Shi_Chi: ["Chihuahua", "Shih-Tzu"],
    Shih_Poo: ["Poodle", "Shih-Tzu"],
    Shiranian: ["Pomeranian", "Shih-Tzu"],
    Shollie: ["Border Collie", "German Shepherd"],
    Shorkie: ["Shih-Tzu", "Yorkie"],
    Siberian_Retriever: ["Husky", "Labrador"],
    Spanador: ["Cavalier King Charles Spaniel", "Labrador"],
    Spanador: ["Cocker Spaniel", "Labrador"],
    Springador: ["Labrador", "Springer Spaniel"],
    Sprocker: ["Cocker Spaniel", "Springer Spaniel"],
    Sprollie: ["Border Collie", "Springer Spaniel"],
    Texas_Healer: ["Australian Cattle Dog", "Australian Shepherd"],
    Valley_Bulldog: ["Boxer", "Bulldog"],
    Yorkiepoo: ["Poodle", "Yorkie"],
    Zuchon: ["Bichon Frise", "Shih-Tzu"],
    // Affenhuahua: ["Affenpinscher", "Chihuahua"],
    // Airedoodle: ["Airedale Terrier", "Poodle"],
    // Dobergi: ["Corgi", "Doberman"],
    // Greygi: ["Corgi", "Greyhound"],
    // Pyrenees_Airedale: ["Airedale Terrier", "Great Pyrenees"],
    // Shigi: ["Corgi", "Shiba Inu"],
    // Spitzgi: ["Corgi", "Spitz"],
    // Westiepoo: ["Poodle", "Westie"],
};

// Choose 0 - 36 for dog1    &    0 - 35 for dog2
//  (Highest number first)

let dog1 = dog1Array[13]
let dog2Array = dog1Array.filter(dog => dog != dog1)
let dog2 = dog2Array[7]

console.log(dog1)
console.log(dog2)

const generator = () => {
    for (let [key, value] of Object.entries(crossbeeds)) {
        if (value.includes(dog1) && value.includes(dog2)) {
            return(key)
        }
    }
    return("I'm sorry, we don't have a result for that combination at the moment.")
}

console.log(generator())